Make repo testable on Binder
euroargodev/OSnet-GulfStream pull request #13
Opened 2022-02-25 14:02 UTC by gmaze

2022-03-01 12:35 UTC, gmaze commented
I think this is ready:

[![Binder](https://img.shields.io/static/v1.svg?logo=Jupyter&label=Binder&message=Click+here+to+try+osnet+online+!&color=blue)](https://mybinder.org/v2/gh/euroargodev/binder-sandbox/pangeo-ml?urlpath=git-pull%3Frepo%3Dhttps%253A%252F%252Fgithub.com%252Feuroargodev%252FOSnet-GulfStream%26urlpath%3Dlab%252Ftree%252FOSnet-GulfStream%252Fdocs%252Fdemo-predictions.ipynb%26branch%3Dbinder)

I decoupled Binder set-up from this repo content using the new [binder-sandbox](https://github.com/euroargodev/binder-sandbox) repo !

2022-03-01 15:23 UTC, EPauthenet requested changes
Le chargement d'une trajectoire Argo ne fonctionne pas et donne cette erreur :
`FileNotFoundError: ['https://www.ifremer.fr/erddap/tabledap/ArgoFloats.nc?data_mode,latitude,longitude,position_qc,time,time_qc,direction,platform_number,cycle_number,config_mission_number,vertical_sampling_scheme,pres,temp,psal,pres_qc,temp_qc,psal_qc,pres_adjusted,temp_adjusted,psal_adjusted,pres_adjusted_qc,temp_adjusted_qc,psal_adjusted_qc,pres_adjusted_error,temp_adjusted_error,psal_adjusted_error&platform_number=~"3901602"&distinct()&orderBy("time,pres")']`

- Sinon tout fonctionne mais avec des warnings de Tensorflow et Panda qui préviennent que certaines fonctions seront plus à jour.

2022-03-02 08:16 UTC, quai20 approved these changes
ça tourne parfaitement de mon côté. Juste un warning de deprec xarray un peu pénible sur 
float ou int `.get_loc`

2022-03-02 09:28 UTC, gmaze commented
> Le chargement d'une trajectoire Argo ne fonctionne pas et donne cette erreur :

ca devait etre momentanee et une erreur du serveur erddap Argo

2022-03-02 09:36 UTC, gmaze commented
Oui tous les warnings c'est penible

C'est a cause de la derniere version de pandas (1.4.0) pour laquelle xarray doit faire une maj, cf https://github.com/pydata/xarray/pull/6195

la aussi, on n'y peut rien et ca devrait disparaitre assez vite avec les nouvelles releases

2022-03-02 09:43 UTC, merged